# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
- group: keyvault
- name: buildConfiguration
  value: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: PowerShell@2
  displayName: 'IoT Central'
  inputs:
    filePath: 'DeploymentScripts/IoTC-Task.ps1'
    arguments: '-ApiToken "$(iotcapikey)" -ConfigPath "Configs/Prod" -AppName "nerf" -ServicePrincipalPassword (ConvertTo-SecureString "$DeploymentPipelineSP" -AsPlainText -Force) -AppId "1783230e-32eb-4410-852b-2d132423b484" -KeyVault "cicd-nerf" -TenantId "72f988bf-86f1-41af-91ab-2d7cd011db47" '
    pwsh: true
    failOnStderr:  true

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Orca (fbd2fc80-d380-4029-bb2e-16b3443ffca2)'
    appType: 'webAppLinux'
    appName: 'SamplePipelineTH'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'



