# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master



pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs:
- job: buildJob
  displayName: buildjob
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'pipelines-dotnet-core.csproj'


  # - script: dotnet build --configuration $(buildConfiguration)
  # displayName: 'dotnet build $(buildConfiguration)'

- job: deployJob
  displayName: My Deployment Job
  steps:
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Orca (fbd2fc80-d380-4029-bb2e-16b3443ffca2)'
      appType: 'webAppLinux'
      appName: 'SamplePipelineTH'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'


