# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Orca (fbd2fc80-d380-4029-bb2e-16b3443ffca2)'
    KeyVaultName: 'troyhopkeyvault'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "API Token:" $(iotcapikey)'
- task: PowerShell@2
  inputs:
    filePath: 'IoTC-Task.ps1'
    pwsh: true
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Orca (fbd2fc80-d380-4029-bb2e-16b3443ffca2)'
    appType: 'webAppLinux'
    appName: 'SamplePipelineTH'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'



